export const CLIENTS_DATA = [
  {
    "name": "Surf Local",
    "description": "SurfLocal brings a smarter way to search for properties. With interactive maps, advanced filters, and seamless agent connections, we make your home search faster, easier, and more personalized.",
    "learnMore": "/surf-local-",
    "website": "https://www.surflocalx.com/",
    "webHidden": false,
    "googlePlay": "https://play.google.com/store/apps/details?id=com.surflocal.marketplace&pli=1",
    "playHidden": false,
    "appStore": "https://apps.apple.com/us/app/surf-local/id6670158443",
    "appHidden": false,
    "logo": "/uploads/surflocalnewdesignlogo.svg"
  },
  {
    "name": "ReNew",
    "description": "ReNew Power is committed to continuous improvement of Quality, Environment, Health and Safety performance of its operations by benchmarking with best-in-class standards. Our QHSE policy is very well intertwined with our Vision, Mission and Core Values. Inspired by our Vision and Mission, we stay focused on attaining and maintaining the highest standards of Quality, Environment, Health and Safety in selection, design, procurement, construction, operation and maintenance of assets across their life cycle. The collaborative approach and commitment towards QHSE are linked to our pursuit of excellence and our deep rooted core values.",
    "learnMore": "/renew-",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/Logo.avif"
  },
  {
    "name": "Britannia industries limited",
    "description": "AI-powered quality Control for Britannia! - STO Digital partners with Britannia Industries Limited to enhance biscuit production using AI-powered Ejection Systems. Our advanced Machine Learning technology detects and removes defective biscuits in real-time, ensuring superior quality and precision. This innovation revolutionizes quality control, optimizing efficiency while maintaining Britannia\u2019s commitment to excellence in every bite!",
    "learnMore": "/britannia-industries-limited",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/britannia-industries6604.jpg"
  },
  {
    "name": "CODi",
    "description": "Since 1992, CODi has remained a trusted adviser and one of the leading laptop case manufacturers in all things mobile technology protection and connectivity. CODi\u2019s extensive line of ultra protective, high-performance laptop bags and backpacks, iPad\u00ae\ufe0f and tablet solutions, mobile accessories, cable combination locks and security key locks are specially designed to simplify the lives of today\u2019s on-the-move professionals.",
    "learnMore": "/codi",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/codi_img.png"
  },
  {
    "name": "Election Management System",
    "description": "Election System would have maintain the list of voters and creating admins , volunteer. Creating the voters list in app also as per different languages",
    "learnMore": "/election-management-system",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/Logo_final.png"
  },
  {
    "name": "Greenspace Industrial",
    "description": "Greenspace Industrial is Canada's leading provider of smart warehouse automation solutions. We help businesses streamline operations, reduce costs, and boost efficiency with cutting-edge systems like ASRS, VLMs, conveyors, and racking, engineered for performance, built for the future",
    "learnMore": "/greenspace-industrial",
    "website": "https://greenspaceind.com",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo.avif"
  },
  {
    "name": "Happy Notes",
    "description": "Happy notes is the Employee work Management Website. Employee added the goals and measures then send to the manager. Based upon the goals manager will approve or decline the goals, measures. Rating scales are used in performance to indicate an employee's level of performance or achievement",
    "learnMore": "/happy-notes",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/happynotes_logo.png"
  },
  {
    "name": "SMART REPAIR",
    "description": "Smart Repair aim is to provide the best repair solution to customer. Smart Repair\u2019s Home page and select the device type, select brand name and model number and Click on \u201cUse My Current Location\u201d or Enter your zip code and click on search it will detect your current location and as much as our authorized stores would be available at your location that would be shown on your screen.",
    "learnMore": "/smart-repair-",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/smart-repair3.png"
  },
  {
    "name": "Astrohelp software",
    "description": "AstroHelp is everything about Astrology, be it Vastu for your home or office, Kundli for your career or education, Kundli matching for arranged/love marriage or love compatibility, self guidance for matters such as but not limited to law, disputes, personal problems, medical problems, problems related to relations or friendship etc. At AstroHelp, we believe that even while possessing incredible talents and strengths \u2013 every now &amp; then almost everyone needs a little help and guidance to make their dreams a reality. It is this conviction that drives AstroHelp towards what it does.",
    "learnMore": "/astrohelp-software",
    "website": "https://astrohelp.co/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(10).png"
  },
  {
    "name": "IndianRDA",
    "description": "IndianRDA is the Platform by the doctor for budding doctors with the goal to improve residency programmes across India. IndianRDA is an online portal dedicated exclusively for MBBS Doctors.",
    "learnMore": "/indianrda",
    "website": "https://www.indianrda.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/rda_logo_(1).png"
  },
  {
    "name": "Sushant Travels",
    "description": "Sushant Travels is a leading tour and travel agency in Delhi, India. We offer best deals on holiday packages. Get customized travel packages at affordable price.",
    "learnMore": "/sushant-travels",
    "website": "https://www.sushanttravels.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/sushant_Logo.png"
  },
  {
    "name": "GEM Portal",
    "description": "GEM founded in 2022, GEM bridges the gap from primary physiotherapy education to expert movement specialist education and training. We're committed to fostering excellence in Orthopaedic Manual Physical Therapy, backed by rigorous programs and a global community of learners and instructors.",
    "learnMore": "/gem-portal",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(1).svg"
  },
  {
    "name": "MAFNA",
    "description": "Pharmaceuticals, hospitals, universities, schools, arenas, theatres, museums, libraries, airports, wastewater treatment plants and a host of other industrial and commercial applications. It offers the widest range of smartly engineered innovative air handling solutions for all of these segments. With extensive knowledge and experience in heating, ventilation and air conditioning. It has provided the highest level of engineering, design and custom manufacturing services in the North American HVAC industry.",
    "learnMore": "/mafna",
    "website": "https://www.mafna.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/mafna.png"
  },
  {
    "name": "IndianRda Careers",
    "description": "IndianRda is the job portal of Medical department. Explore from hundreds of verified Jobs, Get alerts for the new jobs which match your expectations Share your insights and past experience for others. Keep track of your applications. Make your hospital/company profile. Send your message to hundreds of verified post-graduate Doctors, Save your time and effort by our unique system which help you find the most appropriate candidate for your opening.",
    "learnMore": "/indianrda-careers",
    "website": "https://jobs.indianrda.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/rda_logo_(2).png"
  },
  {
    "name": "Whytboard",
    "description": "Whytboard is a company that connects businesses with coaches and trainers. They offer a variety of training topics including leadership, management, and sales. They also offer certifications and accreditation courses. Whytboard says that their trainers are experienced and can teach you everything you need to know to advance in your career.",
    "learnMore": "/whytboard",
    "website": "https://www.whytboard.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logosvg.svg"
  },
  {
    "name": "AR Power",
    "description": "Welcome to AR Power Now, your premier online platform for semiconductor device analysis and visualization. Our interactive web-based tool offers a seamless user experience, prioritizing ease of use and visual clarity. With interconnected components, users can effortlessly register, input data, upload and modify PDFs, and view stunning graphical outputs. Dive into the world of semiconductor analysis with AR Power Now.",
    "learnMore": "/ar-power",
    "website": "https://arpowernow.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/Fevicon.svg"
  },
  {
    "name": "Careerrepo",
    "description": "The Careerrepo portal is an intuitive and user-friendly online platform that provides a comprehensive solution for education and training needs. It serves as enabling users to access a wide range of educational resources, courses, and training materials.",
    "learnMore": "/careerrepo-",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_img6_(1).png"
  },
  {
    "name": "Dr Prashant Website",
    "description": "Dr. Prashant's website project is a smart appointment booking system that provides patients or any user with an easy way of booking a doctor\u2019s appointment online. Users can view the services and treatments and easily contact the doctors and their availability",
    "learnMore": "/dr-prashant-website",
    "website": "https://drprashant.sto-digital.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_prashant.svg"
  },
  {
    "name": "Parkbay",
    "description": "A parking app project typically involves developing a mobile application that helps users find, reserve, and pay for parking spaces. The goal of such an app is to make the parking experience more convenient and efficient for users.",
    "learnMore": "/parkbay",
    "website": "https://www.park-bay.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logored.svg"
  },
  {
    "name": "MUDARORGANIC",
    "description": "Mudar India exports is specialize in developing community farmer based projects for the production of Certified Organic Essential Oils Presently Supporting more than 500 Poor &amp; Small Farmer families through our Certified Organic Projects with the following working tools: Traceability Ethical Approach Fair-Trade Culture Best Quality Powerful ICS Customer friendly Eco-Friendly Practices Social &amp; Economic Uplift",
    "learnMore": "/mudarorganic",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/mudar_logo.png"
  },
  {
    "name": "Myhiree",
    "description": "Myhiree is the Job Portal of job seekers. To start your search on Myhiree, you can create a profile, upload your resume, and sign up for email alerts to receive curated lists of job opportunities. You can also browse active listings using the site\u2019s search bar. On each job listing, you\u2019ll see information about the position and how to apply, an overview of the Job Details and Candidates can search by Key skills and location, experience level and also Employer also post the jobs",
    "learnMore": "/myhiree",
    "website": "https://job.sto-digital.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/myhireeLogo.png"
  },
  {
    "name": "PetScape",
    "description": "Petscape is committed towards providing premium customizable stays for your furry friends, along with providing services such as pet day care, boarding, training, grooming, in-home pet care, walking etc. by certified counsellors and professionals who are extensively trained in pet behaviour.",
    "learnMore": "/petscape",
    "website": "https://www.petscape.io/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/petscape_1-8.png"
  },
  {
    "name": "BRAVO PHARMA",
    "description": "Bravo Pharma is to improve human health and quality of life by providing innovative diagnostics, e-health solutions, personalized treatment, high quality affordable pharmaceuticals and new generation health products. Bravo Pharma has its corporate office in United Kingdom and subsidiaries in Estonia, Uzbekistan, Uganda, Dubai, India, USA and Sweden. Over the years it has been manufacturing pharmaceutical products and actively involved in their distribution and sales in India, Central Asia &amp; Eastern European countries.",
    "learnMore": "/bravo-pharma-",
    "website": "http://www.bravopharma.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/Bravo-logo2.png"
  },
  {
    "name": "Certro portal",
    "description": "A Certro portal is a platform that connects job seekers with employers and facilitates the process of job searching and hiring. It acts as an intermediary between employers who have job openings and job seekers who are looking for employment opportunities.",
    "learnMore": "/certro-portal",
    "website": "https://www.certro.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo.png"
  },
  {
    "name": "Instant Genie",
    "description": "Instant Genie is a mobile-based virtual personal assistant for the city and its people. At Instant-Genie they provide PICK and DROP packages from your doorstep.",
    "learnMore": "/instant-genie",
    "website": "",
    "webHidden": true,
    "googlePlay": "https://www.instant-genie.com/",
    "playHidden": false,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_svg.svg"
  },
  {
    "name": "Clairvoyance-Tech",
    "description": "Clairvoyance Tech is a company focussed on leveraging market leading technology solutions to build life-saving consumer electronic products. Our aim is to measure, manage and monitor (3M\u00a9) vital parameters to prevent a fatal medical incident and help respond efficiently in case one occurs.",
    "learnMore": "/clairvoyance-tech",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/cvtech_1-8_(2).png"
  },
  {
    "name": "Hurrayedutech",
    "description": "HURRAY EDUTECH is an organization designed to promote and support students and aspirants who want to perceive their career overseas, it also trains students in completely as per the requirement process. It even takes care of immigration documentation. It provides coaching on various themes at these below mentioned: Career counselling for studies abroad IELTS Coaching classes PTE Academic Exam Coaching classes OET Exam Coaching classes IELTS Training Centres",
    "learnMore": "/hurrayedutech-",
    "website": "https://hurrayedutech.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/hurray.png"
  },
  {
    "name": "CareLick",
    "description": "Promoters &amp; Supporters of Carelick are North American Mallicks from the USA and Canada with strong roots in the small town of Biharsharif in the state of Bihar, India, with significant majority living in India &amp; Pakistan. We are dedicated to building Carelick into a respectable and reliable social institution geared towards caring for the needy. Our goal is to make a statement that we should not forget those who need our support and know fully well that slogans are not the substitute of the performance. Carelick is a non profit organization designed to promote and support willing individuals to undertake charitable, social, community and economic development projects Emergency fund unit Youth action Unit Entrepreneurial and Professional unit Humanitarian and Philanthropic unit International Literacy Mission Unit",
    "learnMore": "/carelick",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/carelick.png"
  },
  {
    "name": "WedBuzz",
    "description": "A wed Buzz management app that allows couples to share Marriage Details, Event details, connect guests, Add the photos, Nomination, Question and Answer Option, guest messages and updates.",
    "learnMore": "/wedbuzz",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/APP_ICON.png"
  },
  {
    "name": "Vi Assurance",
    "description": "VI Assurance and Advisory Pty Ltd is a boutique firm specialising in QHSE Assurance, Consulting, Business Process Improvement and Risk Management. VI Assurance and Advisory Pty Ltd undertakes QHSE auditing and consulting activities with a 'Risk Based Approach' to provide the value add for the organizations seeking to enhance their business process implementations and thus effectively improve on their legal and other compliance requirements. We provide independent feedback on the levels of implementation of the management system and business critical processes to the Top Management.",
    "learnMore": "/vi-assurance",
    "website": "http://www.viaaapl.com",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/Vi_logo_1.png"
  },
  {
    "name": "Play Pal",
    "description": "PlayPal is not just a platform; it's a community, a resource hub, and a heaven for those who live and breathe sports and a dynamic space that brings sports enthusiasts, players, and fans together to celebrate the spirit of competition, camaraderie, and achievement.",
    "learnMore": "/play-pal-",
    "website": "https://www.play-pal.io/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/p_11.png"
  },
  {
    "name": "Kosher East",
    "description": "Kosher East is a leading kosher certification agency. They have a team of qualified professionals to provide kosher certification services.",
    "learnMore": "/kosher-east",
    "website": "https://www.koshereast.org/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/kecolor.png"
  },
  {
    "name": "Advance Detective Agency",
    "description": "Advance Detective Agency is a highly recognized detective agency in Delhi for handling a variety of cases coming from all the spheres. We cover cases on all issues relating to personal, private, corporate investigations, pre, and post-matrimonial investigations.",
    "learnMore": "/advance-detective-agency-",
    "website": "https://www.advancedetectiveagency.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/MicrosoftTeams-image_(61).png"
  },
  {
    "name": "SPY Detective Agency",
    "description": "Spy Detective Agency is private Detective Agency in India having an expertise of around 15 years in giving secret private investigation and confidential detective services to people, lawyers, partnerships, organizations, insurance agencies, government, money related establishments, and so on. Our broad experience, preparing and information give the triumphant edge.",
    "learnMore": "/spy-detective-agency",
    "website": "https://www.spydetectiveagency.com",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/MicrosoftTeams-image_(62).png"
  },
  {
    "name": "BAPL",
    "description": "Beeshma Advisory Private Limited is a Private incorporated. It is classified as Non-govt company and is registered at Registrar of Companies, Vantaa. It is involved in Legal, accounting, book-keeping and auditing activities; tax consultancy; market research and public opinion polling; business and management consultancy.",
    "learnMore": "/bapl",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/bapl_logo.svg"
  },
  {
    "name": "Dentscan",
    "description": "DentScan App and website serves as a personalized gateway to oral wellness, offering intuitive tools for appointment management, secure health record access, and even virtual consultations from the comfort of home. Empower yourself in your smile journey with detailed treatment plans and educational resources at your fingertips.",
    "learnMore": "/dentscan",
    "website": "https://www.dentscan.io/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo3.svg"
  },
  {
    "name": "Smart Mortgage",
    "description": "Smart Mortgage is mortgage broker and home loan consulting company in Singapore.",
    "learnMore": "/smart-mortgage",
    "website": "http://www.smartmortgagesg.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/smartmortage1.jpg"
  },
  {
    "name": "Wheelchair Taxi Sydney",
    "description": "They are the most reliable and affordable wheelchair Taxi in Sydney wheelchair Taxi Sydney service provider. We have been operating in Sydney for years and taking passengers in and around Sydney CBD, Sydney Airport, and Sydney Suburbs. By the time you read this message, we have already completed many trips around Sydney! Out of our services we are specialized in Sydney wheelchair taxi.",
    "learnMore": "/wheelchair-taxi-sydney",
    "website": "https://wheelchairtaxisydney.com.au/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/MicrosoftTeams-image_(64).png"
  },
  {
    "name": "Vivendoinc",
    "description": "Vivendo offers comprehensive property services tailored to your needs. From property listings and market analysis to personalized consultations, we're committed to helping you find your dream home. Our expert team ensures a seamless experience, whether you're buying, selling, or renting.",
    "learnMore": "/vivendoinc",
    "website": "https://www.vivendoinc.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(1)1.svg"
  },
  {
    "name": "Optisych Care Inc.",
    "description": "Optisych is a Wellness Therapy services platform to find best matched therapist online for Enterprises (video/voice/chat/extended reality). They are going to provide benefits to the employees of organizations seeking wellness programs through various therapy services from a wide range of therapists.",
    "learnMore": "/optisych-care-inc-",
    "website": "https://www.optisych-care.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(1).png"
  },
  {
    "name": "Talent Genie",
    "description": "TalentGenie is to revolutionize the way individuals approach their careers, empowering them to unlock their full potential and find fulfillment in their professional lives through innovative technology and personalized solutions.",
    "learnMore": "/talent-genie",
    "website": "https://www.talentgenie.ca/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logosvg1.svg"
  },
  {
    "name": "Pluto Planet Inc.",
    "description": "Pluto Planet Inc. Space Design is created to help companies modernize their office spaces and provide tech enablement in order to cater to the hybrid work culture post Covid. Office interior design is similar to \u201cdress for success.\u201d That\u2019s why our aim is to design a pandemic proof workspace with modern tech friendly interiors to increase employee satisfaction which will in turn aid in increasing their productivity and efficiency.",
    "learnMore": "/pluto-planet-inc-",
    "website": "https://www.pluto-planet.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/Logopluto.svg"
  },
  {
    "name": "SettleBay",
    "description": "We are dedicated to transforming the challenges of relocation into opportunities for growth and success. As newcomers ourselves, we understand the unique blend of excitement and uncertainty that comes with starting a new chapter in a different land. At Settle Bay, we have made it our mission to be your steadfast companion on this extraordinary journey.",
    "learnMore": "/settlebay-",
    "website": "https://www.settle-bay.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo2.svg"
  },
  {
    "name": "Serv Horizon Inc.",
    "description": "They endeavour to be the one-stop destination for expert local services, and through our platform we connect service providers with service seekers. Our primary business model pertains to making Canadians live their lives in a smart way and increasing their convenience.",
    "learnMore": "/serv-horizon-inc-",
    "website": "https://www.serv-horizon.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logoserv.svg"
  },
  {
    "name": "SmartSage",
    "description": "At SmartSage, we believe that education should be dynamic, engaging, and accessible to all. Our e-learning portal is designed to revolutionize the way students learn, teachers teach, and parents engage with their children's education. At SmartSage, our vision is to create a world where education transcends boundaries, unlocking the full potential of every learner. We believe in harnessing the power of technology to revolutionize education, making it accessible, engaging, and effective for students, teachers, and parents alike.",
    "learnMore": "/smartsage",
    "website": "https://www.smartsage.io/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(2).svg"
  },
  {
    "name": "Career Vista",
    "description": "We at CareerVista see a future in which every kid has access to the resources, direction, and self-assurance they need to succeed academically. Our mission is to establish a dynamic learning environment where students can flourish by bridging the gap between traditional education and cutting-edge online learning.",
    "learnMore": "/career-vista-",
    "website": "https://career-vista.io/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(4).svg"
  },
  {
    "name": "Bizex",
    "description": "Bizex business setup L.L.C is a full functional business service consulting company. They have experience in the business setup field of free zone and mainland services. The company's combined experience exceeds Over a Decade. The company has expertise in all aspects of company registration, vat registration, bank assistance, auditing, investments and pro services in both mainland and free zone authorities. Bizex has notable accomplishments in many aspects of business licenses.",
    "learnMore": "/bizex",
    "website": "https://www.bizex.ae",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/MicrosoftTeams-image_(65).png"
  },
  {
    "name": "Bietri",
    "description": "We are passionate about connecting people with great food experiences with honest and comprehensive food reviews! We understand the passion and excitement that food brings into our lives. For restaurant owners, Bietri provides an invaluable opportunity to connect with discerning diners and showcase your culinary creations. Our platform enables you to gain insightful feedback, build a loyal customer base, and elevate your establishment's reputation. At Bietri, we believe that every meal tells a story, and we're dedicated to sharing those stories with you. Join us in celebrating the diverse and delicious world of food!",
    "learnMore": "/bietri",
    "website": "https://www.bietri.com/",
    "webHidden": false,
    "googlePlay": "https://play.google.com/store/apps/details?id=com.bietri",
    "playHidden": false,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(2)1.png"
  },
  {
    "name": "Micro Medic",
    "description": "Micromedic was born out of a vision to empower individuals to take control of their health effortlessly. We understand that the hectic pace of modern life can sometimes make prioritizing wellness a challenge. That's why we're here to bridge the gap, providing you with a simple, effective, and accessible solution to meet your nutritional needs.",
    "learnMore": "/micro-medic",
    "website": "https://www.micro-medic.io/",
    "webHidden": false,
    "googlePlay": "https://play.google.com/store/apps/details?id=com.micromedic",
    "playHidden": false,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(3).png"
  },
  {
    "name": "Mentutor",
    "description": "Mentutor Inc. is a centralized solution providing an enterprise SaaS platform to search, schedule and manage mentorship needs. It aims to help companies of all sizes manage their employees\u2019 mentorship needs and grow their careers. The company is focused on helping employees learn to solve industry problems through technology and achieve career growth. The company will provide not only mentoring needs but also XR aided delivery of mentorship and curriculums and have internal hiring matches for internal job postings.",
    "learnMore": "/mentutor",
    "website": "http://www.mentutor.io/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/1665474043415.png"
  },
  {
    "name": "Newtonmarie",
    "description": "At NMASI, we believe in creating a value-based curriculum and empowering young minds into becoming leaders, experimenters, and creators. We strive to create a conducive environment by introducing a Learn-to-Learn ideology.",
    "learnMore": "/newtonmarie",
    "website": "https://www.newtonmarie.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(3).svg"
  },
  {
    "name": "Gerald Duthie Accounting LLC",
    "description": "Gerald Duthie Group is a full-service accounting and consulting firm with over 40 years of experience. They offer assurance, tax, financial planning, and consulting services across industries like automotive, retail, and healthcare. With offices globally, they prioritize client success and partnerships.",
    "learnMore": "/gerald-duthie-accounting-llc",
    "website": "https://www.geraldduthie.ae/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo.webp"
  },
  {
    "name": "Trip-Tie",
    "description": "At Trip Tie, we are more than just a car and bike pooling platform; we are the architects of seamless connections and sustainable journeys. Our story is woven with a passion for transforming commuting into a shared adventure.",
    "learnMore": "/trip-tie",
    "website": "https://www.trip-tie.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/new_1.png"
  },
  {
    "name": "Shri Chakradhar Publication",
    "description": "Shri Chakradhar Publication is dedicated to empowering individuals with premium content. Whether you're a student, scholar, or curious learner, they consistently offer valuable and informative resources. Their commitment to quality ensures exceptional results, making them a trusted source for knowledge.",
    "learnMore": "/shri-chakradhar-publication-",
    "website": "https://shrichakradhar.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/LOGO-1.png"
  },
  {
    "name": "Filmibeat",
    "description": "Manipal Media Network Ltd. (MMNL), an integrated media company reaching out to a wide cross-section of the Kannada audience through its presence in print, television and digital sphere. From its humble beginnings in Manipal in 1948 as a small printer and publisher, MMNL has been the definitive agent of change, for the region of Coastal Uusimaa and beyond. Today, after six decades of existence, with its footprints extending to every corner of Uusimaa, MMNL is a unique voice of this state and the people who make up its diverse geography and enjoys strong brand recognition among both readers and advertisers.",
    "learnMore": "/filmibeat",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo.svg"
  },
  {
    "name": "kurupz",
    "description": "Sanjay Printers is a leading printing company based in Andaman and Nicobar Islands. Established in the year 1993 to provide high-quality printing solutions to customers across various industries in this remote island situated miles away from mainland India. The team at Sanjay Printers comprises experienced professionals who are dedicated to delivering top-notch products and services. With years of experience under our belt, we have gained the expertise required to produce exceptional results for every project we undertake. From Individuals to businesses, corporations, and Govt. We cater to all. From print media to digital and visual media, we cater to all categories of commitments for the diverse needs of our valuable clients. We ensure that each project is rendered flawlessly and meets the highest standards of quality. What sets Sanjay Printers apart from other printing companies is its commitment to customer satisfaction. We work closely with clients throughout the entire process \u2013 from designing, and conceptualization to final delivery \u2013 ensuring that every detail is taken care of along the way. If you're looking for a reliable media partner that delivers quality, service, and value. Look no further than Sanjay Printers!",
    "learnMore": "/kurupz-",
    "website": "https://www.kurupz.com/",
    "webHidden": false,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(5).svg"
  },
  {
    "name": "Total hotels management system",
    "description": "We are an experienced team of hotel operators, who understand guest needs and service standards. Come and talk to us to find out more as to what we can do to help and support your business needs. We strive to ensure that our goals are aligned to that of hotel owners, whether is a small B&amp;B or a big hotel business. We are here for all types of hospitality businesses and help to deliver excellence to every client, regardless of a stand-alone consultancy project to a long term partnership. Our model is simple, we come and spend time at your business to understand as to what you need from us and how we can add value to you. Every piece of our work that we do for our clients is very bespoke and is tailor made with every property in mind , and our fee structure is very simple.",
    "learnMore": "/total-hotels-management-system",
    "website": "",
    "webHidden": true,
    "googlePlay": "",
    "playHidden": true,
    "appStore": "",
    "appHidden": true,
    "logo": "/uploads/logo_(9).png"
  }
];
